apiVersion: apps/v1

kind: Deployment

metadata:
  name: udagram-web-app
  labels:
    app: udagram-web-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-web-app
  template:
    metadata:
      labels:
        app: udagram-web-app
    spec:
      containers:
      - name: udagram-web-app
        image: phoenix254/udagram-web-app:v1
        ports:
        - containerPort: 80