apiVersion: v1

kind: Service

metadata:
  name: udagram-web-app
  labels:
    app: udagram-web-app

spec:
  selector:
    app: udagram-web-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
    protocol: TCP
  type: LoadBalancer