apiVersion: v1

kind: Service

metadata:
  name: web-app
  labels:
    service: web-app

spec:
  selector:
    service: web-app
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  type: LoadBalancer