apiVersion: v1

kind: Service

metadata:
  name: feed-service
  labels: 
    app: feed-service

spec:
  selector:
    app: feed-service
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  