apiVersion: apps/v1

kind: Deployment

metadata:
  name: user-service
  labels:
    service: user-service

spec:
  replicas: 2
  selector:
    matchLabels: 
      service: user-service
  template:
    metadata:
      labels:
        service: user-service
    spec:
      containers:
      - name: user-service
        image: phoenix254/udagram-user-service:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: UdagramPostgresqlUsername
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramPostgresqlUsername
        - name: UdagramPostgresqlPassword
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramPostgresqlPassword
        - name: UdagramPostgresqlDatabase
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramPostgresqlDatabase
        - name: UdagramPostgresqlHost
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramPostgresqlHost
        - name: UdagramAWSRegion
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramAWSRegion
        - name: UdagramAWSProfile
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramAWSProfile
        - name: UdagramAWSMediaBucket
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramAWSMediaBucket
        - name: UdagramWebAppUrl
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramWebAppUrl
        - name: UdagramJwtSecret
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: UdagramJwtSecret
      restartPolicy: Always