version: v1

kind: Service

metadata:
  name: reverse-proxy-service
  labels:
    app: reverse-proxy

spec:
  selector:
    app: reverse-proxy
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type:
    LoadBalancer